//
// Generated file, do not edit! Created by opp_msgc 4.3 from broadcast.msg.
//

#ifndef _BROADCAST_M_H_
#define _BROADCAST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
using namespace std;
// }}



/**
 * Class generated from <tt>broadcast.msg</tt> by opp_msgc.
 * <pre>
 * packet Broadcast {
 *     string sourceName;
 *    	simtime_t genTime;
 * }
 * </pre>
 */
class Broadcast : public ::cPacket
{
  protected:
    opp_string sourceName_var;
    simtime_t genTime_var;

  private:
    void copy(const Broadcast& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Broadcast&);

  public:
    Broadcast(const char *name=NULL, int kind=0);
    Broadcast(const Broadcast& other);
    virtual ~Broadcast();
    Broadcast& operator=(const Broadcast& other);
    virtual Broadcast *dup() const {return new Broadcast(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getSourceName() const;
    virtual void setSourceName(const char * sourceName);
    virtual simtime_t getGenTime() const;
    virtual void setGenTime(simtime_t genTime);
};

inline void doPacking(cCommBuffer *b, Broadcast& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Broadcast& obj) {obj.parsimUnpack(b);}


#endif // _BROADCAST_M_H_
